mapfishapp - revert org.json to the version print-lib depends on
downgrade parent's 20180813 version or org.mapfish.print.servlet.MapPrinterServlet.getInfo
throws java.lang.NoSuchMethodError: org.json.JSONWriter.<init>(Ljava/io/Writer;)V